create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    password varchar(255) not null,
    name varchar(50) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_users_email unique (email)
);

create table organizations (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    description text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table organization_members (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    user_id bigint not null,
    role varchar(20) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_organization_member unique (organization_id, user_id),
    constraint ck_organization_member_role check (role in ('OWNER', 'ADMIN', 'MANAGER', 'MEMBER')),
    constraint fk_organization_member_organization foreign key (organization_id) references organizations (id),
    constraint fk_organization_member_user foreign key (user_id) references users (id)
);

create index idx_organization_members_user on organization_members (user_id);
create index idx_organization_members_organization on organization_members (organization_id);
