create table asset_categories (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    name varchar(100) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_asset_category_name unique (organization_id, name),
    constraint fk_asset_category_organization foreign key (organization_id) references organizations (id)
);

create index idx_asset_categories_organization on asset_categories (organization_id);

create table locations (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    name varchar(100) not null,
    description text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_location_name unique (organization_id, name),
    constraint fk_location_organization foreign key (organization_id) references organizations (id)
);

create index idx_locations_organization on locations (organization_id);
