create table assets (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    category_id bigint,
    location_id bigint,
    assigned_user_id bigint,
    public_code varchar(32) not null,
    asset_code varchar(100) not null,
    name varchar(150) not null,
    description text,
    status varchar(20) not null,
    purchase_date date,
    purchase_price numeric(15, 2),
    deleted_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_asset_public_code unique (public_code),
    constraint uk_asset_organization_code unique (organization_id, asset_code),
    constraint ck_asset_status check (status in ('AVAILABLE', 'IN_USE', 'REPAIR', 'LOST', 'DISPOSED')),
    constraint ck_asset_purchase_price check (purchase_price is null or purchase_price >= 0),
    constraint fk_asset_organization foreign key (organization_id) references organizations (id),
    constraint fk_asset_category foreign key (category_id) references asset_categories (id) on delete set null,
    constraint fk_asset_location foreign key (location_id) references locations (id) on delete set null,
    constraint fk_asset_assigned_user foreign key (assigned_user_id) references users (id)
);

create index idx_assets_organization on assets (organization_id);
create index idx_assets_organization_name on assets (organization_id, name);
create index idx_assets_organization_status on assets (organization_id, status);
create index idx_assets_organization_category on assets (organization_id, category_id);
create index idx_assets_organization_location on assets (organization_id, location_id);
