create table asset_histories (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    asset_id bigint not null,
    actor_id bigint not null,
    action_type varchar(30) not null,
    field_name varchar(50),
    before_value text,
    after_value text,
    memo text,
    created_at timestamp with time zone not null,
    constraint ck_asset_history_action check (action_type in (
        'CREATED', 'UPDATED', 'STATUS_CHANGED', 'LOCATION_CHANGED', 'ASSIGNEE_CHANGED', 'DELETED'
    )),
    constraint fk_asset_history_organization foreign key (organization_id) references organizations (id),
    constraint fk_asset_history_asset foreign key (asset_id) references assets (id),
    constraint fk_asset_history_actor foreign key (actor_id) references users (id)
);

create index idx_asset_histories_organization_created on asset_histories (organization_id, created_at desc);
create index idx_asset_histories_asset_created on asset_histories (asset_id, created_at desc);
create index idx_asset_histories_actor on asset_histories (actor_id);
create index idx_asset_histories_action on asset_histories (action_type);
